[ { pattern: /:\bdate\b/, replacement: '2013/09/30' },
  { pattern: /:\bL\b/, replacement: '09/30/2013' },
  { pattern: /:\b1\b/, replacement: '9/30/2013' },
  { pattern: /:\byear\b/, replacement: '2013' },
  { pattern: /:\bYYYY\b/, replacement: '2013' },
  { pattern: /:\bYY\b/, replacement: '13' },
  { pattern: /:\bmonthname\b/, replacement: 'September' },
  { pattern: /:\bMMMM\b/, replacement: 'September' },
  { pattern: /:\bMMM\b/, replacement: 'Sep' },
  { pattern: /:\bmonth\b/, replacement: '09' },
  { pattern: /:\bMM\b/, replacement: '09' },
  { pattern: /:\bmo\b/, replacement: '09' },
  { pattern: /:\bM\b/, replacement: '9' },
  { pattern: /:\bDDDD\b/, replacement: '273' },
  { pattern: /:\bDDD\b/, replacement: '273' },
  { pattern: /:\bday\b/, replacement: '30' },
  { pattern: /:\bDD\b/, replacement: '30' },
  { pattern: /:\bD\b/, replacement: '30' },
  { pattern: /:\bdddd\b/, replacement: 'Monday' },
  { pattern: /:\bddd\b/, replacement: 'Mon' },
  { pattern: /:\bdd\b/, replacement: 'Mo' },
  { pattern: /:\bd\b/, replacement: '1' },
  { pattern: /:\bhour\b/, replacement: '20' },
  { pattern: /:\bHH\b/, replacement: '20' },
  { pattern: /:\bH\b/, replacement: '20' },
  { pattern: /:\bhh\b/, replacement: '08' },
  { pattern: /:\bh\b/, replacement: '8' },
  { pattern: /:\bminute\b/, replacement: '00' },
  { pattern: /:\bmin\b/, replacement: '00' },
  { pattern: /:\bmm\b/, replacement: '00' },
  { pattern: /:\bm\b/, replacement: '0' },
  { pattern: /:\bsecond\b/, replacement: '00' },
  { pattern: /:\bsec\b/, replacement: '00' },
  { pattern: /:\bss\b/, replacement: '00' },
  { pattern: /:\bs\b/, replacement: '0' },
  { pattern: /:\bA\b/, replacement: 'PM' },
  { pattern: /:\ba\b/, replacement: 'pm' },
  { pattern: /:\bP\b/, replacement: 'P' },
  { pattern: /:\bp\b/, replacement: 'p' },
  { pattern: /:\bdirname\b/,
    replacement: 'test/actual/collections_complex' },
  { pattern: /:\bfilename\b/, replacement: 'index.html' },
  { pattern: /:\bpagename\b/, replacement: 'index.html' },
  { pattern: /:\bbasename\b/, replacement: 'index' },
  { pattern: /:\bsrc\b/,
    replacement: 'test/fixtures/pages/index.hbs' },
  { pattern: /:\bdest\b/,
    replacement: 'test/actual/collections_complex/index.html' },
  { pattern: /:\bassets\b/, replacement: '../../assets' },
  { pattern: /:\bext\b/, replacement: '.html' },
  { pattern: /:\bextname\b/, replacement: '.html' },
  { pattern: /:\btitle\b/, replacement: 'home' },
  { pattern: /:\bdescription\b/,
    replacement: 'this-is-the-home-page' },
  { pattern: /:\bslug\b/, replacement: 'home-page' },
  { pattern: /:\bdate\b/,
    replacement: 'mon-sep-30-2013-200000-gmt-0400-eastern-daylight-time' },
  { pattern: /:\bsection\b/, replacement: 'plugins' },
  { pattern: /:\btags\b/, replacement: 'onethree' },
  { pattern: /:\bcategory\b/, replacement: '' },
  { pattern: /:\bnum\b/, replacement: '6' },
  { pattern: /:(0)+/, replacement: [Function] },
  { pattern: /:random\(([^)]+)\)/, replacement: [Function] } ]